package com.openminis.app.gateway

import android.content.Context
import android.content.SharedPreferences


/**
 * [T-local-llm-gateway] Persisted gateway preferences.
 *
 * Same shape as [com.openminis.app.network.NetworkSettings]: one
 * SharedPreferences file plus process-wide @Volatile mirrors, so the accept
 * loop and the auth check read live values without a Context hop and a Settings
 * edit applies to the next request instead of needing an app restart.
 *
 * Defaults are the safe ones: the listener is OFF until the user turns it on,
 * and while it is off nothing binds a port at all. A phone that spent the day on
 * public wifi therefore exposes nothing by default.
 */
object GatewaySettings {
    private const val PREFS = "gateway_settings"

    private const val KEY_ENABLED = "gateway.enabled"
    private const val KEY_PORT = "gateway.port"
    private const val KEY_BIND_LAN = "gateway.bind_lan"
    private const val KEY_TOKEN = "gateway.token"
    private const val KEY_MODEL_ALLOWLIST = "gateway.model_allowlist"
    private const val KEY_DEFAULT_MODEL = "gateway.default_model"
    private const val KEY_REQUIRE_KEY = "gateway.require_key"

    /** 18789 — clear of the 18xxx Android debug band and the 5321 debug server. */
    const val DEFAULT_PORT = 18789

    @Volatile var enabled: Boolean = false
        private set

    @Volatile var port: Int = DEFAULT_PORT
        private set

    /**
     * False binds 127.0.0.1 only — nothing off-device can connect. True binds
     * 0.0.0.0, which puts the phone's own API budget on the LAN, so it also
     * forces a token ([requireKey]).
     */
    @Volatile var bindLan: Boolean = false
        private set

    /** Bearer / x-api-key value. Blank means "no auth" (loopback mode only). */
    @Volatile var token: String = ""
        private set

    /** Model ids the gateway advertises and resolves. Empty = whole agent-loop catalogue. */
    @Volatile var modelAllowlist: List<String> = emptyList()
        private set

    /** Where a client that asks for an unresolvable name is routed instead. */
    @Volatile var defaultModel: String? = null
        private set

    @Volatile var requireKey: Boolean = false
        private set

    fun load(context: Context) {
        val p = prefs(context)
        enabled = p.getBoolean(KEY_ENABLED, false)
        port = p.getInt(KEY_PORT, DEFAULT_PORT).coerceIn(1, 65535)
        bindLan = p.getBoolean(KEY_BIND_LAN, false)
        token = p.getString(KEY_TOKEN, "").orEmpty()
        requireKey = p.getBoolean(KEY_REQUIRE_KEY, false) || bindLan
        defaultModel = p.getString(KEY_DEFAULT_MODEL, "").orEmpty().ifBlank { null }
        modelAllowlist = decodeList(p.getString(KEY_MODEL_ALLOWLIST, "").orEmpty())
    }

    /**
     * Effective token. Never blank while the socket is reachable beyond
     * loopback, nor when the user asked for key enforcement — enforcement
     * matters on loopback too, because another app on the device can open
     * 127.0.0.1.
     */
    fun currentToken(): String {
        val t = token
        if (t.isNotBlank()) return t
        if (bindLan || requireKey) return ephemeralToken
        return ""
    }

    /**
     * Provisioned when auth is required but the field was left empty. It is
     * surfaced in the Settings UI, so it can never be an invisible secret the
     * user cannot read off the screen.
     */
    private val ephemeralToken: String by lazy {
        val bytes = ByteArray(16)
        java.security.SecureRandom().nextBytes(bytes)
        "minis-" + bytes.joinToString("") { "%02x".format(it) }
    }

    /** True when LAN/key is on but the user has not typed a token of their own. */
    fun tokenAutoGenerated(): Boolean = token.isBlank() && (bindLan || requireKey)

    data class State(
        val enabled: Boolean,
        val port: Int,
        val bindLan: Boolean,
        val token: String,
        val requireKey: Boolean,
        val defaultModel: String?,
        val modelAllowlist: List<String>,
    )

    fun snapshot(): State = State(
        enabled = enabled,
        port = port,
        bindLan = bindLan,
        token = token,
        requireKey = requireKey,
        defaultModel = defaultModel,
        modelAllowlist = modelAllowlist,
    )

    /**
     * Persist, reload the volatile mirrors and return the new state. Callers
     * restart the listener when [State.enabled] or [State.port] changed.
     */
    fun update(
        context: Context,
        enabled: Boolean = this.enabled,
        port: Int = this.port,
        bindLan: Boolean = this.bindLan,
        token: String = this.token,
        requireKey: Boolean = this.requireKey,
        defaultModel: String? = this.defaultModel,
        modelAllowlist: List<String> = this.modelAllowlist,
    ): State {
        val next = State(
            enabled = enabled,
            port = port.coerceIn(1, 65535),
            bindLan = bindLan,
            token = token.trim(),
            // LAN exposure implies a key: a phone on cafe wifi must not hand its
            // API budget to whoever can route to the port.
            requireKey = requireKey || bindLan,
            defaultModel = defaultModel?.trim()?.ifBlank { null },
            modelAllowlist = modelAllowlist.map { it.trim() }.filter { it.isNotEmpty() },
        )
        prefs(context).edit()
            .putBoolean(KEY_ENABLED, next.enabled)
            .putInt(KEY_PORT, next.port)
            .putBoolean(KEY_BIND_LAN, next.bindLan)
            .putString(KEY_TOKEN, next.token)
            .putBoolean(KEY_REQUIRE_KEY, next.requireKey)
            .putString(KEY_DEFAULT_MODEL, next.defaultModel.orEmpty())
            .putString(KEY_MODEL_ALLOWLIST, encodeList(next.modelAllowlist))
            .apply()
        load(context)
        return next
    }

    private fun encodeList(items: List<String>): String =
        items.joinToString("|") { it.replace("|", "%7C") }

    private fun decodeList(raw: String): List<String> =
        if (raw.isBlank()) emptyList()
        else raw.split('|').map { it.replace("%7C", "|") }.filter { it.isNotEmpty() }

    private fun prefs(context: Context): SharedPreferences =
        context.applicationContext.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
}
